//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Langben.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYResult
    {
        public string Id { get; set; }
        public string Result { get; set; }
        public string GoldTempId { get; set; }
        public string GoldTempPath { get; set; }
        public string StandardTemp { get; set; }
        public string Style { get; set; }
        public string Remark { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string CreatePerson { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdatePerson { get; set; }
        public Nullable<int> Vertion { get; set; }
        public string InsuranceId { get; set; }
        public string GoldTempName { get; set; }
        public string GoldTempFullPath { get; set; }
    }
}
